# Generated by Django 4.2 on 2023-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnvironmentalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("temp", models.FloatField()),
                ("humi", models.FloatField()),
                ("co2", models.FloatField()),
                ("water_supply", models.FloatField()),
                ("water_supply_cumulative", models.FloatField()),
                ("light", models.FloatField()),
                ("light_cumulative", models.FloatField()),
                ("soil_moisture", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PlantWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("weight", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="WaterLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("waterlevel", models.FloatField()),
            ],
        ),
    ]
