# Generated by Django 4.2 on 2023-07-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EnvironmentalData",
        ),
    ]
